footprint: [[-0.5, -0.4], [-0.5, 0.4], [0.5, 0.4], [0.5, -0.4]]
footprint_padding: 0.01
map_type: costmap

# Coord frame/tf param
transform_tolerance: 0.2 
robot_base_frame: spherebot_torso

# Rate params
update_frequency: 1.0
publish_frequency: 2.0

# Sensor mgmt params
obstacle_range: 5.0
raytrace_range: 5.0

# Layer defs
static_layer:
  subscribe_to_updates: true

obstacle_layer:
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {
    sensor_frame: hokuyo_lidar, 
    data_type: LaserScan, 
    topic: /hokuyo/laser_scan, 
    marking: true, 
    clearing: true }

inflation_layer:
  inflation_radius: 0.55
  cost_scaling_factor: 5.0

