# Coord frame/tf param
global_frame: odom

# Map mgmt params
static_map: false
rolling_window: true
width: 10.0
height: 10.0
resolution: 0.05
origin_x: -30.0
origin_y: -30.0

plugins:
   - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
   - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
